### ISSUE TITLE
docs and args

### ISSUE THREAD

**Issue by coachshea** [rbong/neovim-vifm#5]
First, thank you for the great plugin. As a big fan of both vifm and vim (now neovim), I have always loved the integration between the two and I am very happy to see that this plugin is taking advantage of some of the advanced features of neovim.

I do have two suggestions:

The first is better documentation. There are no vimdocs and so we cannot use :help from inside of vim, but also, the readme file doesn't contain any mention of the variables and reading the source code, it appears that there are many variables available. Having them documented somewhere (docs best, but readme is fine) would help.

My second suggestion is to allow passing options to the vifm commands. I realize this can be a little tricky because you are trying to check for 'isDirectory' to ensure proper handling of ':edit <file>' commands, but maybe an option could be added (ie g:Vifm_options). 

Thanks again, and I hope these suggestions help.

**Comment by rbong** [comment]
Thank you for the suggestions!

I've now moved the usage documentation and variables to vimdocs.

There are a couple variables I mistakenly pushed up that still remain undocumented. These are works in progress. I've left them in, since some people may now be using them. All other variable documentation has been moved from the readme.

There have been requests for passing options to vifm before. The best suggestion I have right now is to use `:let $MYVIFMRC=/path/to/custom/vifmrc` (`$MYVIFMRC` is the real name of the variable). More information in the vimdocs.

This should allow doing everything you can do with options that I know of. I know its a bit awkward if you only want to change one thing temporarily, but given that I do not use this feature, and that I would need to sanitize/check the arguments, it would likely come with some hidden bugs. Also, a single custom configuration will fit most use cases. If the plugin picks up more steam or if someone has a use case that is not met, I will reconsider adding an options variable.
